config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "about/index"
  root  'about#index'
  get "sessions/create"
  match '/signin',to:'sessions#new',via:'get'
  match '/signout',to:'sessions#destroy',via:'delete'
   match '/confirm/:id',to:'users#confirm', as:'user_confirm', via:'get'
   match '/driver/:id',to:'drivers#new',as:'resister_driver', via:'get'

  resources :answers
  resources :questions
  resources :operations
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  def confirm
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :birthday, :reserved_at, :operation_id, :body_part, :first_time, :reservation_id, :URL)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_confirm.html.erb
<h1>確認フォーム</h1>

<p>
  <%= @user.reservation_id %>
  <%= @user.birthday  %>
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :reserved_at %><br>
    <%= f.datetime_select :reserved_at %>
  </div>
  <div class="field">
    <%= f.label :operation_id %><br>
    <%= f.number_field :operation_id %>
  </div>
  <div class="field">
    <%= f.label :body_part %><br>
    <%= f.number_field :body_part %>
  </div>
  <div class="field">
    <%= f.label :first_time %><br>
    <%= f.number_field :first_time %>
  </div>
  <div class="field">
    <%= f.label :reservation_id %><br>
    <%= f.number_field :reservation_id %>
  </div>
  <div class="field">
    <%= f.label :URL %><br>
    <%= f.text_field :URL %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/confirm.html.erb
<h1>確認フォーム</h1>

<p>
  <%= @user.reservation_id %>
  <%= @user.birthday  %>
</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Birthday</th>
      <th>Reserved at</th>
      <th>Operation</th>
      <th>Body part</th>
      <th>First time</th>
      <th>Reservation</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.birthday %></td>
        <td><%= user.reserved_at %></td>
        <td><%= user.operation_id %></td>
        <td><%= user.body_part %></td>
        <td><%= user.first_time %></td>
        <td><%= user.reservation_id %></td>
        <td><%= user.URL %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Reserved at:</strong>
  <%= @user.reserved_at %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @user.operation_id %>
</p>

<p>
  <strong>Body part:</strong>
  <%= @user.body_part %>
</p>

<p>
  <strong>First time:</strong>
  <%= @user.first_time %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @user.reservation_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @user.URL %>
</p>

<h2>この内容に、お間違いありませんか？</h2>
<%= link_to 'OK', new_question_path %> |
<%= link_to 'NO', about_index_path, data: { confirm: 'お手数ですが、クリニックまで再度ご連絡をお願いします。' } %>